### ISSUE TITLE
Markers aren't shown on zoom-in unless they're outside of the view

### ISSUE THREAD

**Issue by RussNelson** [ghybs/Leaflet.FeatureGroup.SubGroup#1]
Not sure what I'm doing wrong here. Not at all. If you visit this URL, it will show you markers, then it will zoom in to the hash location, at which point the markers disappear. If you then zoom out, it shows you the clusters. If you zoom in, still no markers. But if, without changing your zoom level, you pan around, markers will appear. Zoom out, they get clustered. Zoom in, no markers.

It's as if the zooming-in function hides markers rather than revealing them.

http://rths.us/viz2.cgi#11/43.1311/-74.9728

**Comment by ghybs** [comment]
Hi!

It looks like it it caused by your version of [Leaflet.markercluster plugin](https://github.com/Leaflet/Leaflet.markercluster) being outdated.

I copied your code into Plunker, changed the version of that library, and it looks to work: http://plnkr.co/edit/4ZVQlse1YTxJV3uwQo0Z?p=preview

A few notes:
- Do not add your individual markers to the map. Marker Cluster will take care of it. Otherwise, you will see **all** your markers initially on map, until Marker Cluster collects them gradually on zooming out and if they are in the view port.
- You should upgrade Leaflet as well (current stable version is 0.7.7).

Hope this helps.

**Comment by RussNelson** [comment]
HA! Such a simple fix! Thanks so much.
