### ISSUE TITLE
SubGroup Checkbox Toggle

### ISSUE THREAD

**Issue by TinArgus** [ghybs/Leaflet.FeatureGroup.SubGroup#10]
Hello! I have found your plugin to be very useful! Thanks for offering this to the community. In your [Nested Groups](https://ghybs.github.io/Leaflet.FeatureGroup.SubGroup/examples/subGroup-controlLayers-nestedGroups.html) demo, the Child SubGroup checkboxes remain checked when the ParentGroup is unchecked and the SubGroups are not displayed. Is there a way to uncheck the SubGroup checkboxes when the ParentGroup is unchecked so that the layer control reflects what layers are displaying on the map? Thanks again!

**Comment by ghybs** [comment]
Hi,

Thank you for your feedback, it is always highly appreciated! :-)

As for your request, I guess it would be a matter of listening to [`"overlayadd"`](http://leafletjs.com/reference-1.0.3.html#map-overlayadd) and [`"overlayremove"`](http://leafletjs.com/reference-1.0.3.html#map-overlayremove) events and adding/removing the subgroups from map accordingly.
Which by the way, emulates the behaviour of this plugin, so it might become useless…

I think the question is rather what the user expects?

For sure having a checkbox ticked while the subgroup is not on map might be confusing. But in fact it means the subgroup is added to the parent group, and it will be added/removed along with the latter.

But what should happen when all subgroups and parent group are unticked (i.e. removed from map), and user ticks a subgroup (call it A)? Should the parent group be added as well, so that A's layers are visible? What about other subgroups that were previously added to the parent group? Sounds like quite some unexpected consequences of a single tick?

I do not have a clear view of what should be the general behaviour in that case.
But your specific use case might be different.

Hope this helps.

**Comment by TinArgus** [comment]
Thank you for getting back to me and providing your thoughts on the matter. You are right in that different users might expect different actions depending on the application. 

In my application, if subgroup A was turned on, the parent group should also be turned on so that the layers are visible, like you describe. The other subgroups that were checked would be forgotten and would have to be turned on again manually. In this case, turning on a parent group would also turn on all of the subgroups. You're right, this might be an unexpected consequence for most applications and it would lose some of the built-in functionality of the plugin.

One solution to this problem that wouldn't require changing this functionality would be to make the subgroups nested in a tree under the parent group and hidden or 'folded' when the parent group is unticked. This way the subgroup layers could remain checked but would only visible when the parent group is enabled. It also has the added benefit of allowing multiple parent groups and subgroups without cluttering the layer control. There is [another plugin](https://github.com/bambrikii/leaflet-layer-tree-plugin) that has the folding tree action for layers, but it hasn't yet been updated for Leaflet 1.0 and doesn't appear to have the same parent group subgroup relationship. Do you think this sort of display could be integrated with your plugin?

I appreciate your insights and your willingness to troubleshoot specific usages. I'll take a look at overlayAdd and overlayRemove in the meantime and see if I can wrap my head around it. I'm still fairly new to Leaflet, but it's getting easier each day!

**Comment by ghybs** [comment]
Hi,

It seems to me that you have mainly 2 possible solutions, both requiring a custom Layers Control (maybe similar to the plugin you link to):

- A Layers Control that disables / hides / folds subgroups when the parent is unticked / removed from map, as you suggest. You could still use this plugin as-is. As to disabling /enabling back on parent remove / add, listeners on `"overlayremove"` and `"overlayadd"` would probably be a solution.

- A Layers Control that removes subgroups from map when the parent is removed, as I initially imagined. You would no longer need this plugin for this. As to removing subgroups when parent is removed, and adding the parent when a subgroup is added, listeners on the same events could also be a solution, although it could be easy to code it directly in the custom Layers Control.

Good luck!

**Comment by TinArgus** [comment]
Hello, and thanks for the response!

I think the best solution for my problem is probably the first, where your plugin and its functionality is preserved and enhanced with a subgroup folding feature. It does seem like working with "overlayadd" and "overlayremove" is the best way to get the results that I am after. I'll give it some thought and attempt to make a custom layer control that works with your plugin. If I am able to come up with a working solution, or if I run into questions regarding how your plugin works, I'll reopen this topic to share. Thanks again for your ideas on the issue!

**Comment by TinArgus** [comment]
A quick update: I played around with "overlayremove" a little but I had trouble removing specific subgroups with the listener. I may revisit this in the future if I can figure out how to make a custom folding layer control menu, but in the meantime I've come across a workaround.

After searching for a bit I found [another plugin](https://github.com/chugcup/Leaflet.groupedlayercontrol) that will remove or add all members of a group in one click. It is a forked project that is current with Leaflet 1.0. 

This plugin effectively nullifies the FeatureGroup.SubGroup functionality, yet I have found that I need to keep using your plugin and keep the groups coded as SubGroups in order to get [MarkerCluster ](https://github.com/Leaflet/Leaflet.markercluster)to work properly.

I noticed that you are the maintainer of the [MarkerCluster.LayerSupport ](https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport) plugin, which seems to have a similar purpose. Would there be any advantage to using that plugin over FeatureGroup.SubGroup in order to achieve MarkerCluster compatibility? Thanks again for your thoughts!

**Comment by ghybs** [comment]
Hi,

Indeed you need either this plugin (FeatureGroup.SubGroup) or my other one (MCG.LayerSupport) in order to facilitate switching on/off parts of layers in MCG through a Layers Control (or similar), unless you prefer managing calls to MCG's `addLayers` / `removeLayers` yourself.

This plugin (FeatureGroup.SubGroup) is more simple. It works as long as you switch on/off Layer Groups (considered as "subgroups" of an MCG).

The other one (MCG.LayerSupport) is more complex, but it enables switching on/off at the Layer level (marker, etc.).

Hope this helps.
