### ISSUE TITLE
Markers in multiple sub groups

### ISSUE THREAD

**Issue by mjuen** [ghybs/Leaflet.FeatureGroup.SubGroup#13]
Hello, 

I have a problem with markers that are present in more than one sub group. 

If I uncheck one sub group, all items of that group are removed, even though that the other group that is still checked, also contains some of them.

Is this the intended behaviour?

Greetings
Marcel

**Comment by ghybs** [comment]
Hi,

Indeed unfortunately the behaviour when Markers are children of several parent Layer Groups is not totally specified:
- if done programmatically, the last modification wins (add to or remove from map).
- if done through Layers Control, I think the latter re-adds and re-removes overlays as they appear in order, so the bottom-most status wins.

Since we do not track in child layers their containing parent Layer Group(s), it is difficult to determine whether they should still remain on map or be removed.
And to begin with, what should be the default behaviour: remain on map as long as at least one parent Layer Group is? or on the contrary disappear as soon as one of the parent Layer Groups is removed?

All this is also true with stock Leaflet BTW.

I am not sure what general behaviour we could design here.
But in your specific situation, you may very well be able to implement what you need.

**Comment by mjuen** [comment]
I'm actually using the same parent layer.

One small example.

Think of a bucket as a parent group that contains balls in different colors (the subgroups).

You have now something like this:

- Bucket (P)

1. Red (SG)
2. Blue (SG)
3. Green (SG)

P .... Parent group
SG .. Subgroup

There are now some balls that are half green and half blue. So I create one marker (for each special ball) which I add to the subgroups "Green" and "Blue".

If I select green now, I'm able to see also those special balls.The same happens if I start over and select blue right away.

But if I check blue and green and then remove one of those ticks, the balls that have two colors are gone.

**Comment by ghybs** [comment]
Actually I should not have used the "parent" word, I realize now it is confusing in this case, my apologies.

I was referring to Layer Groups in which the Markers are added into, i.e. the Red, Blue or Green SubGroups in your example.

What you describe is indeed the currently "expected" behaviour.

It should be possible to setup some code so that the map behaves as you would like it to, but again that is specific to your requirements and situation.
For instance, any time one of the SubGroup is removed, you could force all other SubGroups that are still on map to "refresh" (like remove then re-add to map).

There could be different needs where on the contrary, users would not expect Markers to appear before _all_ the SubGroups they belong to are added to the map (like an "AND" filter).

Therefore I am not sure we could decide on a generalization that could be implemented in this plugin.

Again, this is not specific to this plugin. Leaflet behaves exactly like this.

**Comment by mjuen** [comment]
I see. Well, in this case I'll figure something out that works for me.

Thanks a lot for your time!

**Comment by josetom** [comment]
@mjuen : I have the exact same use case that you have mentioned here. Have you found a solution for the same ?
