### ISSUE TITLE
Fails to remove layer from a geojson

### ISSUE THREAD

**Issue by Lucki** [ghybs/Leaflet.FeatureGroup.SubGroup#14]
I've tried to dynamically remove a marker from a geojson but it fails presumably because of 

https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup/blob/c7ec78b0cf13be39b00d46beb50c954b8b4c78bb/src/subgroup.js#L149-L151

See https://github.com/Leaflet/Leaflet.markercluster/issues/915

It seems the layer is expected in `this._layers` but not found. I can manually inspect and track the layer down to `this._parentGroup._featureGroup._layers`.

As I used multiple marker clusters before totally fine I wanted to use this as a drop in replacement to combine them and was confused why removing the markers suddenly stopped working.

I'm not using `hasLayer` by myself so this is kind of a bummer.

---

It seems a workaround is to dump the layers manually into the subgroup:
~~~ js
geojson.getLayers().forEach(layer => {
    subgroup.addLayer(layer);
});
~~~

**Comment by ghybs** [comment]
Hi,

Please can you kindly describe how you use the plugin / add your Layers?
Ideally provide a live reproduction example, e.g. using http://leafletjs.com/edit

**Comment by Lucki** [comment]
Just uncomment the one you want to see in the `index.html`:
* Removing without a subGroup works in `works.js`
* Removing fails with a subGroup in `fails.js`

https://plnkr.co/edit/q2sZqZqgXN3PWCEb

**Comment by ghybs** [comment]
Hi,

Thank you for the details and for the reproduction example!

I am not sure I understand the point of assigning a child Layer of your GeoJSON Layer Group to a separate `marker` variable, and expecting to remove it from the subgroup, whereas the latter knows only the GeoJSON Layer Group?

It is true that it will work in the case of MCG, but because the latter has a tweaked behaviour, as described in the issue you point to.

In both cases (MCG and subgroup), simply keep a reference to your GeoJSON Layer Group and remove it from MCG/subgroup when needed.
```js
const cluster = L.markerClusterGroup()
const subgroup = L.featureGroup.subGroup(cluster)

const group = L.geoJSON(data).addTo(subgroup) // same with cluster instead of subgroup

// When needed
subgroup.removeLayer(group) // same with cluster
```

Fixed version in both `fails.js` and `works.js` files: https://plnkr.co/edit/wnhnep9kpINU66Vl

**Comment by Lucki** [comment]
Thanks for pointing me in the right direction. Unknowingly I was under the impression the provided workaround is how it should behave.
The solutions is to remove or add points to the correct geojson feature group - but if the parent is a MarkerCluster to remove or add from that instead.
