### ISSUE TITLE
Bulk adding and removing Markers

### ISSUE THREAD

**Issue by hagai26** [ghybs/Leaflet.FeatureGroup.SubGroup#5]
I would like to use `addLayers`and `removeLayers` from Leaflet.markercluster.
I can see that if on the ctor I pass markers array it uses them, but how can I use these methods afterwards?

Something like:
`mySubGroup .addLayers(markerList)`
instead of:

```
for (let marker of marker_list) {
    marker.addTo(mySubGroup);
}
```

**Comment by ghybs** [comment]
Hi again,

Hmm good point.

Internally, the subgroup will use MCG's `addLayers` when it is added to the map.
So if you add your markers one by one while the subgroup is off map, you would have no performance penalty.

Now if you really want to avoid the `for` loop, you could pass a Layer Group rather an array of markers. It will be added to MCG which now supports groups as if they were arrays. It should work, even though I have not tested it.

Using a Layer Group rather than an array should also cover the case where you are adding markers while the subgroup is already on map.

Hopefully you can switch to a Layer Group. If not, it could be interesting for this plugin to support arrays as well, since one of its main usage is with MCG.
Please feel free to submit a PR! :-)

Hope this helps.

**Comment by hagai26** [comment]
On my case subgroups are already on the map.
I'm getting markers in chunks and I'm adding them to a previously added subgroup.

I didn't understand how to figure out what you have suggested with Layer Group.

I thought on just adding a method like `_addLayers` which will call the MCG `addLayers` method or do the foreach itself when !parentGroup instanceof LG.
Is this possible?

**Comment by ghybs** [comment]
Hi,

I meant `mySubGroup.addLayer(layerGroup)`, I think it should work (it should add `layerGroup` to the parent group, i.e. MCG, which will get the individual markers and internally use `addLayers`).
I agree this is not really optimal…

Did you solve your issue, since you closed the topic?

**Comment by hagai26** [comment]
Work like a charm.

```
let layer_group = L.layerGroup(marker_list);
mySubGroup.addLayer(layer_group);
```

10x!

**Comment by ghybs** [comment]
Thank you for your feedback!

Sorry I realize I skipped a few steps in my explanation…
